<script setup lang="ts">
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { Plus, RefreshCw, SlidersHorizontal, ArrowUp, ArrowDown, Download, MapPin } from '@lucide/vue';
import CustomerShell from '../../Layouts/CustomerShell.vue';
import MTrackOpenStreetMap from '../../Components/MTrackOpenStreetMap.vue';
import PlaceMap from '../../Components/PlaceMap.vue';
import GeofenceEditor from '../../Components/GeofenceEditor.vue';
import DeviceConnect from '../../Components/DeviceConnect.vue';
import RecordPagination from '../../Components/RecordPagination.vue';
import { displayTime as time, type Tracker, type Fence, type Crossing, type Pagination } from '../../Components/TrackingTypes';
const props = defineProps<{
    activeModule: string; allowedModules: string[]; canManageDevices: boolean; canManageGeofences: boolean;
    isAdmin: boolean; basePath: string; selectedTenant: number | null; tenants: { id: number; name: string }[]; canViewLogs: boolean;
    unclaimed: { id: number; imei: string; last_seen_at: string }[];
    trackers: Tracker[]; geofences: Fence[]; events: Pagination<Crossing>; counts: Record<string, number>;
    activity: Pagination<{ id: number; action: string; actor: string; occurred_at: string }> | null;
    ingestion: Pagination<{ id: number; status: string; device_id: number | null; occurred_at: string }> | null;
    filters: { from: string; to: string; tracker?: number; fence?: number; direction?: string; tab?: string };
    preferences: { widgets: string[]; density?: string; refresh_seconds?: number };
    connection: { host: string; port: number }; discovery: { imei: string; last_seen_at: string } | null; refreshedAt: string;
}>();
const titles: Record<string, [string, string]> = { dashboard: ['Dashboard', 'Your latest positions, device status, and geofence activity.'], events: ['Events', 'Review crossings and activity logs within a precise reporting period.'], my_fleets: ['Devices', 'Connect, identify, and manage the trackers in your workspace.'], geofence: ['Geofence', 'Define boundaries and choose when entries and exits are recorded.'] };
const title = computed(() => titles[props.activeModule]!);
const slug = computed(() => props.activeModule === 'my_fleets' ? 'devices' : props.activeModule);
const search = ref(''); const deviceStatus = ref(''); const setup = ref(false); const customize = ref(false);
const editorOpen = ref(false); const editingFence = ref<Fence | null>(null); const selectedFence = ref<Fence | null>(null);
const deleteForm = useForm({}); const deleteId = ref<number | null>(null);
const renameId = ref<number | null>(null); const renameForm = useForm({ display_name: '', business_label: '' });
const connectionId = ref<number | null>(null);
const assignId = ref<number | null>(null); const assignForm = useForm({ tenant_id: '', display_name: '' });
const layout = useForm({ widgets: [...props.preferences.widgets], density: props.preferences.density ?? 'comfortable', refresh_seconds: props.preferences.refresh_seconds ?? 15 });
const filter = useForm({ from: props.filters.from, to: props.filters.to, tracker: props.filters.tracker ?? '', fence: props.filters.fence ?? '', direction: props.filters.direction ?? '', tenant: props.selectedTenant || '', tab: props.filters.tab ?? 'tracking' });
const tab = ref(props.filters.tab ?? 'tracking');
const names: Record<string, string> = { summary: 'Status summary', map: 'Live map', devices: 'Devices', activity: 'Recent crossings' };
const descriptions: Record<string, string> = { summary: 'Reporting status and crossing counts for the selected period.', map: 'Latest GPS positions with individual report timestamps.', devices: 'Device name, status, speed, and most recent report.', activity: 'The five most recent geofence entries and exits.' };
const visibleTrackers = computed(() => props.trackers.filter(t => `${t.display_name} ${t.imei ?? ''} ${t.customer ?? ''}`.toLowerCase().includes(search.value.toLowerCase()) && (!deviceStatus.value || (deviceStatus.value === 'reporting' ? isReporting(t) : !isReporting(t)))));
const fences = computed(() => props.geofences.filter(f => `${f.name} ${f.customer ?? ''}`.toLowerCase().includes(search.value.toLowerCase())));
const markers = computed(() => props.trackers.map(t => ({ ...t, label: t.display_name, subtitle: `Last GPS report: ${time(t.last_seen_at)}` })));
const reporting = computed(() => props.trackers.filter(isReporting).length);
const reportLink = computed(() => `${props.basePath}/reports/places.csv?${new URLSearchParams(Object.fromEntries(Object.entries({ ...props.filters, tenant: props.selectedTenant || '' }).filter(([k,v]) => k !== 'tab' && v !== '' && v !== undefined && v !== null).map(([k,v]) => [k, String(v)])))}`);
function eventName(type: string) { return ({ geofence_entry: 'Entered', geofence_exit: 'Exited', online: 'Reporting resumed', offline: 'Offline', stale: 'Report overdue', no_data: 'No data' } as Record<string,string>)[type] ?? type.replaceAll('_', ' '); }
function switchTab(value: string) { router.get(`${props.basePath}/events`, { ...props.filters, tenant: props.selectedTenant || '', tab: value }, { preserveScroll: true }); }
function isReporting(t: Tracker) { return !['offline', 'stale', 'no_data'].includes(t.status); }
function status(t: Tracker) { return !t.last_seen_at ? 'Waiting for GPS' : isReporting(t) ? t.status.replaceAll('_', ' ') : 'Not reporting'; }
function applyFilters() { filter.tab = tab.value; filter.get(`${props.basePath}/${slug.value}`, { preserveScroll: true, preserveState: false }); }
function changeScope() { filter.tracker = ''; filter.fence = ''; applyFilters(); }
function openFence(fence: Fence | null = null) { editingFence.value = fence; editorOpen.value = true; deleteId.value = null; }
function move(index: number, direction: number) { const next = index + direction; if (next >= 0 && next < layout.widgets.length) [layout.widgets[index], layout.widgets[next]] = [layout.widgets[next]!, layout.widgets[index]!]; }
function openLayout() { layout.widgets = [...props.preferences.widgets]; layout.density = props.preferences.density ?? 'comfortable'; layout.refresh_seconds = props.preferences.refresh_seconds ?? 15; customize.value = true; }
function saveLayout() { layout.post(`${props.basePath}/dashboard/preferences`, { preserveScroll: true, onSuccess: () => customize.value = false }); }
function rename(t: Tracker) { renameId.value = t.id; renameForm.display_name = t.display_name; renameForm.clearErrors(); }
let poll: ReturnType<typeof setInterval>; let lastRefresh = Date.now();
onMounted(() => { poll = setInterval(() => { const seconds = props.preferences.refresh_seconds ?? 15; if (seconds && Date.now() - lastRefresh >= seconds * 1000 && !document.hidden && !setup.value && !customize.value && !editorOpen.value && !renameId.value && !assignId.value && !connectionId.value && !deleteId.value) { lastRefresh = Date.now(); router.reload({ only: ['trackers', 'events', 'counts', 'refreshedAt'] }); } }, 1000); });
onUnmounted(() => clearInterval(poll));
</script>

<template>
    <Head :title="title[0]" />
    <CustomerShell :active="activeModule" :allowed="allowedModules" :base-path="basePath" :is-admin="isAdmin">
        <div :class="{ 'density-compact': preferences.density === 'compact' }">
            <header class="page-heading"><div><div class="eyebrow">{{ isAdmin ? 'PLATFORM' : 'WORKSPACE' }} / {{ title[0].toUpperCase() }}</div><h1>{{ title[0] }}</h1><p>{{ title[1] }}</p></div><div class="actions"><button v-if="activeModule === 'dashboard'" class="btn" :aria-expanded="customize" @click="openLayout"><SlidersHorizontal :size="15" />Configure dashboard</button><button v-if="activeModule === 'my_fleets' && canManageDevices && !isAdmin" class="btn-primary" :aria-expanded="setup" @click="setup = !setup"><Plus :size="15" />Connect device</button><button v-if="activeModule === 'geofence' && canManageGeofences && !editorOpen" class="btn-primary" @click="openFence()"><Plus :size="15" />Create geofence</button></div></header>
            <section v-if="isAdmin" class="scope-bar"><label class="field">Customer scope<select v-model="filter.tenant" @change="changeScope"><option value="">All customers</option><option v-for="tenant in tenants" :key="tenant.id" :value="tenant.id">{{ tenant.name }}</option></select></label><p class="muted">{{ selectedTenant ? 'Showing records for the selected customer.' : 'Platform view · records across all customers.' }}</p></section>
            <DeviceConnect v-if="setup && !isAdmin" :connection="connection" :discovery="discovery" @close="setup = false" />
            <section v-if="customize && activeModule === 'dashboard'" class="panel" aria-labelledby="layout-title">
                <div class="panel-head"><div><h2 id="layout-title">Configure your dashboard</h2><p class="muted">Preferences affect your account only. Changes apply when saved.</p></div><button class="btn" :disabled="layout.processing" @click="customize = false">Cancel</button></div>
                <form @submit.prevent="saveLayout"><div class="configuration-grid panel-body"><div><div class="section-label">Visible sections · display order</div><div v-for="(widget, index) in layout.widgets" :key="widget" class="widget-setting"><div><strong>{{ names[widget] }}</strong><p class="muted">{{ descriptions[widget] }}</p></div><div class="actions"><button class="icon-button" type="button" :disabled="index === 0" :aria-label="`Move ${names[widget]} up`" @click="move(index, -1)"><ArrowUp :size="16" /></button><button class="icon-button" type="button" :disabled="index === layout.widgets.length - 1" :aria-label="`Move ${names[widget]} down`" @click="move(index, 1)"><ArrowDown :size="16" /></button><button class="btn" type="button" @click="layout.widgets.splice(index, 1)">Hide</button></div></div><p v-if="!layout.widgets.length" class="muted">No sections selected. Add one below or save an empty dashboard.</p><div class="actions space-top"><button v-for="widget in Object.keys(names).filter(w => !layout.widgets.includes(w))" :key="widget" class="btn" type="button" @click="layout.widgets.push(widget)"><Plus :size="13" />{{ names[widget] }}</button></div></div><div><div class="section-label">Display and refresh</div><label class="field">Table density<select v-model="layout.density"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label class="field">Automatic refresh<select v-model.number="layout.refresh_seconds"><option :value="0">Manual only</option><option :value="15">Every 15 seconds</option><option :value="30">Every 30 seconds</option><option :value="60">Every minute</option></select><small>Pauses while forms are open or this tab is hidden.</small></label><button class="btn" type="button" @click="layout.widgets = ['summary', 'map', 'devices', 'activity']; layout.density = 'comfortable'; layout.refresh_seconds = 15">Restore defaults</button><p v-for="error in layout.errors" :key="error" class="field-error">{{ error }}</p></div></div><footer class="save-bar"><span class="muted">{{ layout.widgets.length }} sections selected</span><div class="actions"><button class="btn" type="button" @click="customize = false">Cancel</button><button class="btn-primary" :disabled="layout.processing">{{ layout.processing ? 'Saving…' : 'Save configuration' }}</button></div></footer></form>
            </section>
            <template v-if="activeModule === 'dashboard'">
                <div v-if="!trackers.length" class="notice"><strong>No devices in this scope.</strong> <Link v-if="allowedModules.includes('my_fleets')" :href="`${basePath}/devices`" class="text-link">Open devices</Link> to connect or manage a tracker.</div>
                <template v-for="widget in preferences.widgets" :key="widget">
                    <div v-if="widget === 'summary'" class="summary-grid"><div class="summary-card"><span>Devices</span><strong>{{ trackers.length }}</strong><small>In the current scope</small></div><div class="summary-card"><span>Recently reporting</span><strong>{{ reporting }}</strong><small>GPS within 10 minutes</small></div><div class="summary-card"><span>Entries</span><strong>{{ counts.geofence_entry ?? 0 }}</strong><small>{{ filters.from }} through {{ filters.to }} UTC</small></div><div class="summary-card"><span>Exits</span><strong>{{ counts.geofence_exit ?? 0 }}</strong><small>{{ filters.from }} through {{ filters.to }} UTC</small></div></div>
                    <section v-if="widget === 'map'" class="panel"><div class="panel-head"><div><h2>Latest positions</h2><p class="muted">Recorded GPS locations · positions may predate the last page refresh.</p></div><span class="count-label">{{ trackers.filter(t => t.latitude !== null).length }} located</span></div><MTrackOpenStreetMap v-if="trackers.some(t => t.latitude !== null)" :markers="markers" min-height="380px" :zoom="12" /><div v-else class="empty"><MapPin class="empty-icon" :size="24" /><h2>Waiting for a GPS position</h2><p>A device needs power, mobile data, and a GPS fix before its position can appear.</p></div></section>
                    <section v-if="widget === 'devices'" class="panel"><div class="panel-head"><h2>Device status</h2><Link v-if="allowedModules.includes('my_fleets')" :href="`${basePath}/devices`" class="btn">View devices</Link></div><div v-if="!trackers.length" class="empty"><p>No connected devices in this scope.</p></div><div v-else class="table-wrap"><table class="customer-table"><thead><tr><th>Device</th><th>Status</th><th>Speed</th><th>Last GPS report</th></tr></thead><tbody><tr v-for="tracker in trackers" :key="tracker.id"><td><strong>{{ tracker.display_name }}</strong><small v-if="isAdmin">{{ tracker.customer }}</small></td><td><span class="status" :class="{ online: isReporting(tracker) }">{{ status(tracker) }}</span></td><td>{{ tracker.speed === null ? '—' : `${Math.round(tracker.speed)} km/h` }}</td><td>{{ time(tracker.last_seen_at) }}</td></tr></tbody></table></div></section>
                    <section v-if="widget === 'activity'" class="panel"><div class="panel-head"><h2>Recent crossings</h2><Link v-if="allowedModules.includes('events')" :href="`${basePath}/events`" class="btn">View events</Link></div><div v-if="!events.data.length" class="empty"><h2>No crossings in this period</h2><p>Events begin after the first location establishes an inside/outside baseline.</p></div><div v-else class="table-wrap"><table class="customer-table"><thead><tr><th>Device</th><th>Event</th><th>Geofence</th><th>Time (UTC)</th></tr></thead><tbody><tr v-for="event in events.data.slice(0,5)" :key="event.id"><td>{{ event.device }}</td><td>{{ eventName(event.type) }}</td><td>{{ event.place }}</td><td>{{ time(event.occurred_at) }}</td></tr></tbody></table></div></section>
                </template><section v-if="!preferences.widgets.length" class="panel empty"><h2>Your dashboard is empty</h2><p>Add sections using Configure dashboard.</p></section>
            </template>
            <template v-if="activeModule === 'my_fleets'">
                <section v-if="isAdmin && unclaimed.length" class="panel"><div class="panel-head"><div><h2>Connected, awaiting ownership</h2><p class="muted">Up to 100 most recently connected unclaimed trackers · platform administrators only.</p></div></div><div class="table-wrap"><table class="customer-table"><thead><tr><th>IMEI</th><th>Last connection</th><th>Action</th></tr></thead><tbody><tr v-for="device in unclaimed" :key="device.id"><td class="mono">{{ device.imei }}</td><td>{{ time(device.last_seen_at) }}</td><td><button class="btn" @click="assignId = null; connectionId = device.id; assignForm.tenant_id = ''; assignForm.display_name = ''">Assign to customer</button></td></tr></tbody></table></div></section>
                <section v-if="renameId" class="panel"><form class="panel-body" @submit.prevent="renameForm.put(`/customer/trackers/${renameId}`, { preserveScroll: true, onSuccess: () => renameId = null })"><h2>Rename device</h2><label class="field space-top">Device name<input v-model="renameForm.display_name" maxlength="255" required /><span class="field-error">{{ renameForm.errors.display_name }}</span></label><div class="actions"><button class="btn" type="button" @click="renameId = null">Cancel</button><button class="btn-primary" :disabled="renameForm.processing">{{ renameForm.processing ? 'Saving…' : 'Save name' }}</button></div></form></section>
                <section v-if="(assignId || connectionId) && isAdmin" class="panel"><form class="panel-body" @submit.prevent="assignForm.post(connectionId ? `/admin/connections/${connectionId}/assign` : `/admin/devices/${assignId}/assign`, { preserveScroll: true, onSuccess: () => { assignId = null; connectionId = null; } })"><h2>{{ connectionId ? 'Assign connected device' : 'Change device ownership' }}</h2><label class="field space-top">Device name<input v-model="assignForm.display_name" maxlength="120" required /></label><p class="muted">Future tracking belongs to the selected customer. Review the destination before saving.</p><label class="field space-top">Customer<select v-model="assignForm.tenant_id" required><option value="">Choose customer</option><option v-for="tenant in tenants" :key="tenant.id" :value="tenant.id">{{ tenant.name }}</option></select></label><p v-for="error in assignForm.errors" :key="error" class="field-error">{{ error }}</p><div class="actions"><button class="btn" type="button" @click="assignId = null; connectionId = null">Cancel</button><button class="btn-primary" :disabled="assignForm.processing">{{ assignForm.processing ? 'Saving…' : 'Save assignment' }}</button></div></form></section>
                <section class="panel"><div class="table-toolbar"><label class="field grow">Search devices<input v-model="search" type="search" placeholder="Name, IMEI, or customer" /></label><label class="field">Reporting status<select v-model="deviceStatus"><option value="">All statuses</option><option value="reporting">Recently reporting</option><option value="offline">Not reporting</option></select></label><span class="muted">{{ visibleTrackers.length }} of {{ trackers.length }} devices</span></div><div v-if="!trackers.length" class="empty"><h2>No devices yet</h2><p>{{ isAdmin ? 'No assigned devices in this customer scope.' : 'Send the configuration SMS and verify your tracker to claim it.' }}</p><button v-if="!isAdmin && canManageDevices" class="btn-primary" @click="setup = true">Connect device</button></div><div v-else class="table-wrap"><table class="customer-table"><thead><tr><th>Device</th><th v-if="isAdmin">Customer</th><th>Status</th><th>Last GPS report</th><th>Coordinates</th><th>Actions</th></tr></thead><tbody><tr v-for="tracker in visibleTrackers" :key="tracker.id"><td><strong>{{ tracker.display_name }}</strong><small class="mono">{{ tracker.imei ?? `Device #${tracker.id}` }}</small></td><td v-if="isAdmin">{{ tracker.customer ?? 'Unassigned' }}</td><td><span class="status" :class="{ online: isReporting(tracker) }">{{ status(tracker) }}</span></td><td>{{ time(tracker.last_seen_at) }}</td><td class="mono">{{ tracker.latitude === null ? 'Not reported' : `${tracker.latitude.toFixed(5)}, ${tracker.longitude?.toFixed(5)}` }}</td><td><div class="actions"><Link v-if="allowedModules.includes('events')" :href="`${basePath}/events?tracker=${tracker.id}`" class="btn">Events</Link><button v-if="!isAdmin && canManageDevices" class="btn" @click="rename(tracker)">Rename</button><button v-if="isAdmin" class="btn" @click="connectionId = null; assignId = tracker.id; assignForm.tenant_id = String(tracker.tenant_id); assignForm.display_name = tracker.display_name">Assign</button></div></td></tr><tr v-if="!visibleTrackers.length"><td :colspan="isAdmin ? 6 : 5">No devices match these filters.</td></tr></tbody></table></div></section>
            </template>
            <template v-if="activeModule === 'geofence'">
                <GeofenceEditor v-if="editorOpen" :key="editingFence?.id ?? 'new'" :fence="editingFence" :trackers="trackers" :base-path="basePath" :is-admin="isAdmin" :tenants="tenants" :selected-tenant="selectedTenant" @close="editorOpen = false" />
                <section v-if="!editorOpen" class="panel"><div class="table-toolbar"><label class="field grow">Search geofences<input v-model="search" type="search" placeholder="Name or customer" /></label><span class="muted">{{ fences.length }} of {{ geofences.length }} geofences</span></div><div v-if="!geofences.length" class="empty"><MapPin :size="26" class="empty-icon" /><h2>Create your first boundary</h2><p>Use a circle for a radius or draw a polygon around a custom area.</p><button v-if="canManageGeofences" class="btn-primary" @click="openFence()">Create geofence</button></div><div v-else class="table-wrap"><table class="customer-table"><thead><tr><th>Geofence</th><th>Boundary</th><th>Devices</th><th>Recording</th><th>Actions</th></tr></thead><tbody><tr v-for="fence in fences" :key="fence.id"><td><strong>{{ fence.name }}</strong><small v-if="isAdmin">{{ fence.customer }}</small></td><td>{{ fence.shape_type === 'circle' ? `Circle · ${fence.shape_geometry.radius} m` : `Polygon · ${fence.shape_geometry.points?.length} points` }}</td><td>{{ fence.tracker_ids.length ? `${fence.tracker_ids.length} selected` : 'All customer devices' }}</td><td>{{ [fence.entrance_alert_enabled ? 'Entries' : '', fence.exit_alert_enabled ? 'Exits' : ''].filter(Boolean).join(' & ') || 'Paused' }}</td><td><div class="actions"><button class="btn" @click="selectedFence = selectedFence?.id === fence.id ? null : fence">Preview</button><button v-if="canManageGeofences" class="btn" @click="openFence(fence)">Edit</button><button v-if="canManageGeofences" class="btn-danger" @click="deleteId = fence.id">Delete</button></div></td></tr><tr v-if="!fences.length"><td colspan="5">No geofences match your search.</td></tr></tbody></table></div></section>
                <section v-if="deleteId && !editorOpen" class="panel"><div class="panel-body"><h2>Delete {{ geofences.find(f => f.id === deleteId)?.name }}?</h2><p class="muted">This stops monitoring this boundary. Recorded events remain available. The boundary cannot be restored automatically.</p><div class="actions space-top"><button class="btn" :disabled="deleteForm.processing" @click="deleteId = null">Cancel</button><button class="btn-danger" :disabled="deleteForm.processing" @click="deleteForm.delete(`${basePath}/places/${deleteId}`, { preserveScroll: true, onSuccess: () => { deleteId = null; selectedFence = null; } })">{{ deleteForm.processing ? 'Deleting…' : 'Delete geofence' }}</button></div></div></section>
                <section v-if="selectedFence && !editorOpen" class="panel"><div class="panel-head"><h2>{{ selectedFence.name }} · saved boundary</h2><button class="btn" @click="selectedFence = null">Close preview</button></div><PlaceMap :key="selectedFence.id" :shape="selectedFence.shape_type" :geometry="selectedFence.shape_geometry" /></section>
            </template>
            <template v-if="activeModule === 'events'">
                <nav class="view-tabs" aria-label="Event views"><button :aria-current="tab === 'tracking' ? 'page' : undefined" :class="{ selected: tab === 'tracking' }" @click="switchTab('tracking')">Tracking events</button><button v-if="canViewLogs" :aria-current="tab === 'activity' ? 'page' : undefined" :class="{ selected: tab === 'activity' }" @click="switchTab('activity')">Activity logs</button><button v-if="isAdmin" :aria-current="tab === 'ingestion' ? 'page' : undefined" :class="{ selected: tab === 'ingestion' }" @click="switchTab('ingestion')">Ingestion logs</button></nav>
                <section class="panel"><form class="panel-body filters" @submit.prevent="applyFilters"><label class="field">From (UTC)<input v-model="filter.from" type="date" required /></label><label class="field">Through (UTC)<input v-model="filter.to" type="date" required /></label><template v-if="tab === 'tracking'"><label class="field">Device<select v-model="filter.tracker"><option value="">All devices</option><option v-for="device in trackers" :key="device.id" :value="device.id">{{ device.display_name }}</option></select></label><label class="field">Geofence<select v-model="filter.fence"><option value="">All geofences</option><option v-for="fence in geofences" :key="fence.id" :value="fence.id">{{ fence.name }}</option></select></label><label class="field">Event type<select v-model="filter.direction"><option value="">All event types</option><option value="geofence_entry">Entries</option><option value="geofence_exit">Exits</option><option value="online">Reporting resumed</option><option value="offline">Offline</option><option value="stale">Report overdue</option><option value="no_data">No data</option></select></label></template><button class="btn-primary" :disabled="filter.processing">{{ filter.processing ? 'Applying…' : 'Apply filters' }}</button><p v-for="error in filter.errors" :key="error" class="field-error">{{ error }}</p></form><div class="applied-scope">Applied period: {{ filters.from }} 00:00 through {{ filters.to }} 23:59 UTC. Exports use the applied filters.</div></section>
                <template v-if="tab === 'tracking'"><div class="report-summary"><span><strong>{{ events.total }}</strong> matching events</span><span><strong>{{ counts.geofence_entry ?? 0 }}</strong> entries</span><span><strong>{{ counts.geofence_exit ?? 0 }}</strong> exits</span></div><section class="panel"><div class="panel-head"><h2>Tracking events</h2><a :href="reportLink" class="btn"><Download :size="14" />Export CSV</a></div><div v-if="!events.data.length" class="empty"><h2>No events match the applied filters</h2><p>Try another period, device, or geofence. Crossings start after the initial position baseline.</p></div><div v-else class="table-wrap"><table class="customer-table"><thead><tr><th>Device</th><th>Event</th><th>Geofence</th><th>Time (UTC)</th><th>Record</th></tr></thead><tbody><tr v-for="event in events.data" :key="event.id"><td><strong>{{ event.device }}</strong></td><td><span class="status" :class="{ online: event.type === 'geofence_entry' }">{{ eventName(event.type) }}</span></td><td>{{ event.place }}</td><td>{{ time(event.occurred_at) }}</td><td class="mono">#{{ event.id }}</td></tr></tbody></table></div><RecordPagination :records="events" /></section></template>
                <section v-if="tab === 'activity' && activity" class="panel"><div class="panel-head"><div><h2>Activity logs</h2><p class="muted">Recorded account and workspace changes. Sensitive request data is excluded.</p></div></div><div v-if="!activity.data.length" class="empty"><h2>No activity in this period</h2></div><div v-else class="table-wrap"><table class="customer-table"><thead><tr><th>Action</th><th>Performed by</th><th>Time (UTC)</th><th>Record</th></tr></thead><tbody><tr v-for="log in activity.data" :key="log.id"><td>{{ log.action.replaceAll('_', ' ').replaceAll('.', ' · ') }}</td><td>{{ log.actor }}</td><td>{{ time(log.occurred_at) }}</td><td class="mono">#{{ log.id }}</td></tr></tbody></table></div><RecordPagination :records="activity" /></section>
                <section v-if="tab === 'ingestion' && ingestion" class="panel"><div class="panel-head"><div><h2>Ingestion logs</h2><p class="muted">Payload processing records. Unclaimed native packets are retained separately until ownership is assigned.</p></div></div><div v-if="!ingestion.data.length" class="empty"><h2>No ingestion records in this period</h2></div><div v-else class="table-wrap"><table class="customer-table"><thead><tr><th>Record</th><th>Device</th><th>Processing status</th><th>Received (UTC)</th></tr></thead><tbody><tr v-for="log in ingestion.data" :key="log.id"><td class="mono">#{{ log.id }}</td><td>{{ log.device_id ? `Device #${log.device_id}` : 'Unassigned' }}</td><td><span class="status" :class="{ online: log.status === 'normalized' }">{{ log.status }}</span></td><td>{{ time(log.occurred_at) }}</td></tr></tbody></table></div><RecordPagination :records="ingestion" /></section>
            </template>
            <footer class="refresh-note actions"><RefreshCw :size="13" /><span>Last refreshed {{ time(refreshedAt) }} · {{ preferences.refresh_seconds === 0 ? 'Manual refresh' : `Checks every ${preferences.refresh_seconds ?? 15} seconds` }}</span><button class="btn" @click="router.reload()">Refresh now</button></footer>
        </div>
    </CustomerShell>
</template>
